const adminMockData = {
  universities: [
    { id: 1, name: "Oxford University", location: "UK", rank: 1 },
    { id: 2, name: "Harvard University", location: "USA", rank: 2 },
    { id: 3, name: "Stanford University", location: "USA", rank: 3 },
    { id: 4, name: "MIT", location: "USA", rank: 4 },
    { id: 5, name: "University of Cambridge", location: "UK", rank: 5 },
    {
      id: 6,
      name: "California Institute of Technology",
      location: "USA",
      rank: 6,
    },
    { id: 7, name: "Princeton University", location: "USA", rank: 7 },
    { id: 8, name: "University of Chicago", location: "USA", rank: 8 },
    { id: 9, name: "Yale University", location: "USA", rank: 9 },
    { id: 10, name: "University of Toronto", location: "Canada", rank: 10 },
  ],
  students: [
    {
      id: 1,
      name: "Joshua Adamu",
      university: "Oxford University",
      matricNumber: "OXF123456",
    },
    {
      id: 2,
      name: "Mary Johnson",
      university: "Harvard University",
      matricNumber: "HAR234567",
    },
    {
      id: 3,
      name: "Samuel Olatunji",
      university: "Stanford University",
      matricNumber: "STN345678",
    },
    {
      id: 4,
      name: "Grace Enobong",
      university: "MIT",
      matricNumber: "MIT456789",
    },
    {
      id: 5,
      name: "Michael Thompson",
      university: "University of Cambridge",
      matricNumber: "CAM567890",
    },
    {
      id: 6,
      name: "Chinedu Okoro",
      university: "California Institute of Technology",
      matricNumber: "CIT678901",
    },
    {
      id: 7,
      name: "Jessica Smith",
      university: "Princeton University",
      matricNumber: "PRI789012",
    },
    {
      id: 8,
      name: "Ifeoma Adeyemi",
      university: "University of Chicago",
      matricNumber: "UCH890123",
    },
    {
      id: 9,
      name: "David Graham",
      university: "Yale University",
      matricNumber: "YAL901234",
    },
    {
      id: 10,
      name: "Sarah Williams",
      university: "University of Toronto",
      matricNumber: "UTO012345",
    },
  ],
  lecturers: [
    {
      id: 1,
      name: "Dr. Eloisse Motunrayo",
      department: "Computer Science",
      university: "Oxford University",
    },
    {
      id: 2,
      name: "Dr. Nathaniel Graham",
      department: "Engineering",
      university: "Harvard University",
    },
    {
      id: 3,
      name: "Prof. Sarah Williams",
      department: "Physics",
      university: "Stanford University",
    },
    {
      id: 4,
      name: "Prof. Adebayo Ibrahim",
      department: "Chemistry",
      university: "University of Cambridge",
    },
    {
      id: 5,
      name: "Prof. Funmi Adeyemi",
      department: "Geography",
      university: "California Institute of Technology",
    },
    {
      id: 6,
      name: "Prof. Samuel Olayinka",
      department: "Sociology",
      university: "Princeton University",
    },
    {
      id: 7,
      name: "Prof. Grace Enobong",
      department: "Law",
      university: "University of Chicago",
    },
    {
      id: 8,
      name: "Prof. Idongesit Okon",
      department: "Political Science",
      university: "Yale University",
    },
    {
      id: 9,
      name: "Prof. Enitan Akpan",
      department: "Economics",
      university: "University of Toronto",
    },
    {
      id: 10,
      name: "Prof. Joseph Akin",
      department: "History",
      university: "MIT",
    },
  ],
  createdRequests: [
    {
      id: 1,
      student: "Joshua Adamu",
      university: "Oxford University",
      lecturer: "Dr. Eloisse Motunrayo",
      date: "Jan 1, 2025",
    },
    {
      id: 2,
      student: "Mary Johnson",
      university: "Harvard University",
      lecturer: "Dr. Nathaniel Graham",
      date: "Jan 2, 2025",
    },
    {
      id: 3,
      student: "Samuel Olatunji",
      university: "Stanford University",
      lecturer: "Prof. Sarah Williams",
      date: "Jan 3, 2025",
    },
    {
      id: 4,
      student: "Grace Enobong",
      university: "MIT",
      lecturer: "Prof. Joseph Akin",
      date: "Jan 4, 2025",
    },
    {
      id: 5,
      student: "Michael Thompson",
      university: "University of Cambridge",
      lecturer: "Prof. Adebayo Ibrahim",
      date: "Jan 5, 2025",
    },
    {
      id: 6,
      student: "Chinedu Okoro",
      university: "California Institute of Technology",
      lecturer: "Prof. Funmi Adeyemi",
      date: "Jan 6, 2025",
    },
    {
      id: 7,
      student: "Jessica Smith",
      university: "Princeton University",
      lecturer: "Prof. Samuel Olayinka",
      date: "Jan 7, 2025",
    },
    {
      id: 8,
      student: "Ifeoma Adeyemi",
      university: "University of Chicago",
      lecturer: "Prof. Grace Enobong",
      date: "Jan 8, 2025",
    },
    {
      id: 9,
      student: "David Graham",
      university: "Yale University",
      lecturer: "Prof. Idongesit Okon",
      date: "Jan 9, 2025",
    },
    {
      id: 10,
      student: "Sarah Williams",
      university: "University of Toronto",
      lecturer: "Prof. Enitan Akpan",
      date: "Jan 10, 2025",
    },
  ],
  completedRequests: [
    {
      id: 1,
      student: "Joshua Adamu",
      university: "Oxford University",
      lecturer: "Dr. Eloisse Motunrayo",
      date: "Jan 11, 2025",
    },
    {
      id: 2,
      student: "Mary Johnson",
      university: "Harvard University",
      lecturer: "Dr. Nathaniel Graham",
      date: "Jan 12, 2025",
    },
    {
      id: 3,
      student: "Samuel Olatunji",
      university: "Stanford University",
      lecturer: "Prof. Sarah Williams",
      date: "Jan 13, 2025",
    },
    {
      id: 4,
      student: "Grace Enobong",
      university: "MIT",
      lecturer: "Prof. Joseph Akin",
      date: "Jan 14, 2025",
    },
    {
      id: 5,
      student: "Michael Thompson",
      university: "University of Cambridge",
      lecturer: "Prof. Adebayo Ibrahim",
      date: "Jan 15, 2025",
    },
    {
      id: 6,
      student: "Chinedu Okoro",
      university: "California Institute of Technology",
      lecturer: "Prof. Funmi Adeyemi",
      date: "Jan 16, 2025",
    },
    {
      id: 7,
      student: "Jessica Smith",
      university: "Princeton University",
      lecturer: "Prof. Samuel Olayinka",
      date: "Jan 17, 2025",
    },
    {
      id: 8,
      student: "Ifeoma Adeyemi",
      university: "University of Chicago",
      lecturer: "Prof. Grace Enobong",
      date: "Jan 18, 2025",
    },
    {
      id: 9,
      student: "David Graham",
      university: "Yale University",
      lecturer: "Prof. Idongesit Okon",
      date: "Jan 19, 2025",
    },
    {
      id: 10,
      student: "Sarah Williams",
      university: "University of Toronto",
      lecturer: "Prof. Enitan Akpan",
      date: "Jan 20, 2025",
    },
  ],
  activeRequests: [
    {
      id: 1,
      student: "Joshua Adamu",
      university: "Oxford University",
      lecturer: "Dr. Eloisse Motunrayo",
      status: "In Progress",
      date: "Jan 21, 2025",
    },
    {
      id: 2,
      student: "Mary Johnson",
      university: "Harvard University",
      lecturer: "Dr. Nathaniel Graham",
      status: "In Progress",
      date: "Jan 22, 2025",
    },
    {
      id: 3,
      student: "Samuel Olatunji",
      university: "Stanford University",
      lecturer: "Prof. Sarah Williams",
      status: "In Progress",
      date: "Jan 23, 2025",
    },
    {
      id: 4,
      student: "Grace Enobong",
      university: "MIT",
      lecturer: "Prof. Joseph Akin",
      status: "In Progress",
      date: "Jan 24, 2025",
    },
    {
      id: 5,
      student: "Michael Thompson",
      university: "University of Cambridge",
      lecturer: "Prof. Adebayo Ibrahim",
      status: "In Progress",
      date: "Jan 25, 2025",
    },
    {
      id: 6,
      student: "Chinedu Okoro",
      university: "California Institute of Technology",
      lecturer: "Prof. Funmi Adeyemi",
      status: "In Progress",
      date: "Jan 26, 2025",
    },
    {
      id: 7,
      student: "Jessica Smith",
      university: "Princeton University",
      lecturer: "Prof. Samuel Olayinka",
      status: "In Progress",
      date: "Jan 27, 2025",
    },
    {
      id: 8,
      student: "Ifeoma Adeyemi",
      university: "University of Chicago",
      lecturer: "Prof. Grace Enobong",
      status: "In Progress",
      date: "Jan 28, 2025",
    },
    {
      id: 9,
      student: "David Graham",
      university: "Yale University",
      lecturer: "Prof. Idongesit Okon",
      status: "In Progress",
      date: "Jan 29, 2025",
    },
    {
      id: 10,
      student: "Sarah Williams",
      university: "University of Toronto",
      lecturer: "Prof. Enitan Akpan",
      status: "In Progress",
      date: "Jan 30, 2025",
    },
  ],
};

export const fetchAdminMockData = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(adminMockData);
    }, 1000); // Simulate API delay
  });
};
